/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/farm.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function FarmLand(props) {
  const { nodes, materials } = useGLTF("./public/models/farm.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.waterhole.geometry}
        material={materials["Material.010"]}
        position={[1.46, 1.123, 3.479]}
        rotation={[Math.PI, -1.191, Math.PI]}
        scale={[-0.419, -0.059, -0.462]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.stoneFloor}
        position={[0.785, 1.498, -5.099]}
        rotation={[-3.139, -0.301, -3.141]}
        scale={[0.079, 0.032, 0.079]}
      />
      <mesh
        geometry={nodes.hut_small.geometry}
        material={materials["Material.008"]}
        position={[2.824, 1.502, -8.2]}
        rotation={[0, 0.604, 0]}
        scale={[0.023, 0.03, 0.023]}
      />
      <mesh
        geometry={nodes.fence_2.geometry}
        material={materials["Material.010"]}
        position={[1.817, 1.483, -3.626]}
        rotation={[-3.119, -1.113, 3.13]}
        scale={[-0.382, -0.054, -0.421]}
      />
      <mesh
        geometry={nodes.fence_1.geometry}
        material={materials["Material.010"]}
        position={[2.095, 1.343, -0.166]}
        rotation={[-Math.PI, 0.453, -Math.PI]}
        scale={[-0.371, -0.052, -0.409]}
      />
      <mesh
        geometry={nodes.cover_wood_3004.geometry}
        material={materials.trunckdos}
        position={[4.45, 1.611, 3.462]}
        rotation={[-1.453, -0.921, 1.104]}
        scale={[0.023, 0.52, 0.086]}
      />
      <mesh
        geometry={nodes.cover_wood_3001.geometry}
        material={materials.trunck}
        position={[4.5, 1.411, 1.114]}
        rotation={[1.6, 0.07, 1.173]}
        scale={[0.015, 0.33, 0.055]}
      />
      <mesh
        geometry={nodes.cart.geometry}
        material={materials["Material.010"]}
        position={[0.686, 1.593, -8.216]}
        rotation={[3.027, 0.334, -2.901]}
        scale={[-0.188, -0.026, -0.208]}
      />
      <mesh
        geometry={nodes.Steak2.geometry}
        material={materials["02 - Default"]}
        position={[-1.33, 0.749, -1.09]}
        rotation={[0, 0.42, 0]}
        scale={-0.011}
      />
      <mesh
        geometry={nodes.Steak1.geometry}
        material={materials["02 - Default"]}
        position={[5.548, -0.414, -2.224]}
        rotation={[0, 0.42, 0]}
        scale={0.005}
      />
      <group
        position={[1.618, 1.476, 3.045]}
        rotation={[-0.238, -0.281, -0.066]}
        scale={[0.009, 0.01, 0.012]}
      >
        <mesh
          geometry={nodes.bridge_wood.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.bridge_wood_1.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <mesh
        geometry={nodes.box.geometry}
        material={materials["Material.010"]}
        position={[6.067, 1.456, -5.318]}
        rotation={[Math.PI, -0.42, Math.PI]}
        scale={[-0.193, -0.027, -0.213]}
      />
      <mesh
        geometry={nodes.barrel_2.geometry}
        material={materials["Material.010"]}
        position={[1.032, 1.545, -8.42]}
        rotation={[2.478, -0.787, -2.514]}
        scale={[-0.303, -0.042, -0.334]}
      />
      <mesh
        geometry={nodes.barrel_1.geometry}
        material={materials["Material.010"]}
        position={[1.356, 1.468, -8.691]}
        rotation={[Math.PI, -0.42, Math.PI]}
        scale={[-0.335, -0.047, -0.369]}
      />
      <mesh
        geometry={nodes.bag.geometry}
        material={materials["Material.010"]}
        position={[0.681, 1.556, -8.196]}
        rotation={[2.443, -1.145, 2.437]}
        scale={[-0.272, -0.038, -0.3]}
      />
      <mesh
        geometry={nodes.tree_3.geometry}
        material={materials.trees}
        position={[7.19, 1.404, -4.004]}
        rotation={[-Math.PI, 0.266, -Math.PI]}
        scale={[0.106, 0.125, 0.106]}
      />
      <mesh
        geometry={nodes.tree_2.geometry}
        material={materials.trees}
        position={[-2.7, 1.364, -5.603]}
        rotation={[-Math.PI, 0.921, -Math.PI]}
        scale={[0.192, 0.184, 0.192]}
      />
      <mesh
        geometry={nodes.tree_1.geometry}
        material={materials.trees}
        position={[8.805, 0.927, -5.498]}
        rotation={[0, -0.914, 0]}
        scale={[0.258, 0.304, 0.258]}
      />
      <group
        position={[-5.549, 4.635, 6.575]}
        rotation={[0.009, 0.366, -0.085]}
        scale={[2.671, 2.658, 2.658]}
      >
        <mesh geometry={nodes.Cone001_1.geometry} material={materials.gray} />
        <mesh
          geometry={nodes.Cone001_2.geometry}
          material={materials.obsidiana}
        />
      </group>
      <mesh
        geometry={nodes.rock_2003.geometry}
        material={materials["Material.027"]}
        position={[-3.318, 1.126, -1.326]}
        rotation={[0.14, -0.939, 1.745]}
        scale={1.198}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials["Material.040"]}
        position={[5.234, 1.512, -5.28]}
        rotation={[3.14, 0, -3.135]}
        scale={[0.06, 0.023, 0.06]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials["Material.042"]}
        position={[5.678, 1.504, -5.928]}
        rotation={[-3.14, 1.201, -3.139]}
        scale={[0.055, 0.022, 0.055]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={materials["Material.044"]}
        position={[4.079, 1.512, -6.659]}
        rotation={[-3.079, 1.221, 3.076]}
        scale={[0.06, 0.014, 0.06]}
      />
      <mesh
        geometry={nodes.rock_2005.geometry}
        material={materials["Material.058"]}
        position={[-8.158, 4.018, 0.524]}
        rotation={[1.418, -1.337, 2.847]}
        scale={1.21}
      />
      <mesh
        geometry={nodes.rock_2004.geometry}
        material={materials["Material.059"]}
        position={[-8.11, 4.007, 1.729]}
        rotation={[-3.117, -0.726, -1.496]}
        scale={1.204}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.009"]}
        position={[1.529, 1.51, -4.907]}
        rotation={[-3.053, -0.581, -3.081]}
        scale={[0.062, 0.015, 0.062]}
      />
      <mesh
        geometry={nodes.tree_1013.geometry}
        material={materials["trees.006"]}
        position={[-7.827, 4.143, 0.306]}
        rotation={[0, 1.063, 0]}
        scale={[0.308, 0.362, 0.308]}
      />
      <mesh
        geometry={nodes.rock_1001.geometry}
        material={materials["Material.025"]}
        position={[-0.956, 4.427, 5.234]}
        rotation={[0.439, 0.396, -1.117]}
        scale={[0.616, 0.317, 0.708]}
      />
      <mesh
        geometry={nodes.rock_5003.geometry}
        material={materials["Material.060"]}
        position={[6.632, 1.032, 1.593]}
        rotation={[0.11, 0.591, -0.107]}
        scale={[0.542, 0.313, 0.476]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["stone.002"]}
        position={[10.19, 0.932, -1.669]}
        rotation={[0.496, 0.93, -0.894]}
        scale={[0.237, 0.399, 0.215]}
      />
      <mesh
        geometry={nodes.rock_1002.geometry}
        material={materials["Material.061"]}
        position={[-3.829, 0.959, -5.94]}
        rotation={[1.026, 0.845, -0.412]}
        scale={[0.646, 0.333, 0.742]}
      />
      <mesh
        geometry={nodes.grass_1a003.geometry}
        material={materials["plants.006"]}
        position={[2.79, 1.569, -5.328]}
        rotation={[-0.951, -1.242, -0.654]}
        scale={[0.022, 0.043, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a004.geometry}
        material={materials["plants.007"]}
        position={[2.251, 1.497, -3.498]}
        rotation={[-2.664, -0.995, -1.979]}
        scale={[0.019, 0.026, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a005.geometry}
        material={materials["plants.008"]}
        position={[2.708, 1.5, -1.89]}
        rotation={[-2.968, 0.838, -2.97]}
        scale={[0.018, 0.017, 0.001]}
      />
      <mesh
        geometry={nodes.grass_3002.geometry}
        material={materials["plants.009"]}
        position={[-1.541, 4.897, 4.581]}
        rotation={[1.601, 0.82, -1.98]}
        scale={[0.149, 0.149, 0.13]}
      />
      <mesh
        geometry={nodes.grass_3003.geometry}
        material={materials["plants.010"]}
        position={[6.208, 1.394, 1.209]}
        rotation={[-2.737, 1.273, 2.388]}
        scale={[0.087, 0.087, 0.075]}
      />
      <mesh
        geometry={nodes.grass_1a006.geometry}
        material={materials["plants.011"]}
        position={[5.417, 1.326, 1.206]}
        rotation={[0.075, -1.396, -0.054]}
        scale={[0.019, 0.026, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a007.geometry}
        material={materials["plants.012"]}
        position={[7.179, 1.901, -2.492]}
        rotation={[-0.572, 0.504, 0.715]}
        scale={[0.025, 0.034, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a008.geometry}
        material={materials["plants.013"]}
        position={[7.878, 1.491, -6.006]}
        rotation={[-0.399, 0.719, 0.483]}
        scale={[0.025, 0.034, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a009.geometry}
        material={materials["plants.014"]}
        position={[7.634, 1.448, -6.506]}
        rotation={[-3.074, -0.406, -3.048]}
        scale={[0.027, 0.054, 0.001]}
      />
      <mesh
        geometry={nodes.bush001.geometry}
        material={materials["plants.015"]}
        position={[2.679, 1.486, -5.681]}
        rotation={[-0.184, 0.162, -0.013]}
        scale={[0.373, 0.097, 0.373]}
      />
      <mesh
        geometry={nodes.grass_3004.geometry}
        material={materials["plants.016"]}
        position={[-2.034, 1.511, -7.005]}
        rotation={[-3.073, 0.973, 3.034]}
        scale={[0.074, 0.074, 0.065]}
      />
      <mesh
        geometry={nodes.grass_3005.geometry}
        material={materials["plants.017"]}
        position={[2.446, 1.483, -0.714]}
        rotation={[0, -1.017, 0]}
        scale={[0.074, 0.074, 0.065]}
      />
      <mesh
        geometry={nodes.grass_1a010.geometry}
        material={materials["plants.018"]}
        position={[1.509, 1.404, 0.319]}
        rotation={[-0.283, 0.317, 0.114]}
        scale={[0.022, 0.043, 0.001]}
      />
      <mesh
        geometry={nodes.bush002.geometry}
        material={materials["plants.019"]}
        position={[7.691, 1.294, 0.325]}
        rotation={[0.055, 0.206, -0.168]}
        scale={[0.446, 0.12, 0.452]}
      />
      <mesh
        geometry={nodes.grass_1a011.geometry}
        material={materials["plants.020"]}
        position={[6.912, 2.285, 3.583]}
        rotation={[0, 0.621, -0.603]}
        scale={[0.025, 0.034, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a012.geometry}
        material={materials["plants.021"]}
        position={[1.878, 1.395, 3.639]}
        rotation={[-2.682, -1.271, -2.294]}
        scale={[0.022, 0.043, 0.001]}
      />
      <mesh
        geometry={nodes.bush003.geometry}
        material={materials["plants.022"]}
        position={[-2.068, 1.466, -5.556]}
        rotation={[-0.006, 0.303, -0.027]}
        scale={[0.244, 0.064, 0.244]}
      />
      <mesh
        geometry={nodes.grass_1a013.geometry}
        material={materials["plants.023"]}
        position={[2.576, 0.799, -9.56]}
        rotation={[2.581, -0.601, -3.107]}
        scale={[0.027, 0.054, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a014.geometry}
        material={materials["plants.024"]}
        position={[5.124, 0.454, -9.46]}
        rotation={[2.921, -0.658, -2.418]}
        scale={[0.027, 0.054, 0.001]}
      />
      <mesh
        geometry={nodes.bush004.geometry}
        material={materials["plants.025"]}
        position={[2.931, 1.401, 1.238]}
        rotation={[-0.004, 0.047, 0.049]}
        scale={[0.293, 0.077, 0.293]}
      />
      <mesh
        geometry={nodes.grass_3006.geometry}
        material={materials["plants.026"]}
        position={[-0.619, 1.543, -2.453]}
        rotation={[0.282, 0.986, 0.251]}
        scale={[0.074, 0.074, 0.065]}
      />
      <mesh
        geometry={nodes.grass_1a015.geometry}
        material={materials["plants.027"]}
        position={[-0.75, 1.512, -3.14]}
        rotation={[-0.597, -1.085, -0.625]}
        scale={[0.025, 0.024, 0.001]}
      />
      <mesh
        geometry={nodes.rock_2006.geometry}
        material={materials["Material.062"]}
        position={[1.157, 0.992, 0.195]}
        rotation={[-2.49, 1.214, -2.006]}
        scale={[0.628, 1.275, 1.275]}
      />
      <mesh
        geometry={nodes.grass_3007.geometry}
        material={materials["plants.028"]}
        position={[9.772, 1.742, 1.943]}
        rotation={[3.126, -0.868, -2.941]}
        scale={[0.096, 0.096, 0.083]}
      />
      <mesh
        geometry={nodes.grass_1a017.geometry}
        material={materials["plants.030"]}
        position={[10.467, 1.272, -0.032]}
        rotation={[2.923, -0.951, 2.676]}
        scale={[0.028, 0.054, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a016.geometry}
        material={materials["plants.029"]}
        position={[11.347, -0.356, 0.641]}
        rotation={[2.091, 0.789, -1.753]}
        scale={[0.026, 0.025, 0.001]}
      />
      <mesh
        geometry={nodes.grass_3008.geometry}
        material={materials["plants.031"]}
        position={[10.139, 1.339, -1.841]}
        rotation={[0.155, 0.159, -0.278]}
        scale={[0.096, 0.096, 0.083]}
      />
      <mesh
        geometry={nodes.grass_3009.geometry}
        material={materials["plants.032"]}
        position={[2.57, 1.521, -5.383]}
        rotation={[0.191, 1.076, 0.114]}
        scale={[0.076, 0.076, 0.066]}
      />
      <mesh
        geometry={nodes.grass_1a018.geometry}
        material={materials["plants.033"]}
        position={[-2.466, 4.507, 2.331]}
        rotation={[-2.675, -0.269, -1.957]}
        scale={[0.027, 0.026, 0.001]}
      />
      <mesh
        geometry={nodes.grass_1a019.geometry}
        material={materials["plants.034"]}
        position={[-2.686, 4.218, 0.803]}
        rotation={[-2.379, -0.548, -1.951]}
        scale={[0.029, 0.028, 0.001]}
      />
      <mesh
        geometry={nodes.bush005.geometry}
        material={materials["plants.035"]}
        position={[-3.949, 5.131, 1.429]}
        rotation={[-0.378, 0.37, -0.219]}
        scale={[0.346, 0.09, 0.346]}
      />
      <mesh
        geometry={nodes.toad_2004.geometry}
        material={materials["plants.036"]}
        position={[1.901, 1.586, -2.022]}
        rotation={[-0.043, 0.656, -0.071]}
        scale={[0.104, 0.053, 0.104]}
      />
      <mesh
        geometry={nodes.toad_3b002.geometry}
        material={materials["plants.037"]}
        position={[-3.44, 5.085, 0.972]}
        rotation={[0.122, 1.085, -0.5]}
        scale={[0.154, 0.115, 0.154]}
      />
      <mesh
        geometry={nodes.toad_2005.geometry}
        material={materials["plants.038"]}
        position={[-2.683, 2.776, -2.682]}
        rotation={[0.825, 0.979, -1.433]}
        scale={[0.104, 0.053, 0.104]}
      />
      <mesh
        geometry={nodes.toad_1b002.geometry}
        material={materials["plants.039"]}
        position={[3.863, 1.502, 1.424]}
        rotation={[-3.13, 1.16, 3.124]}
        scale={[0.121, 0.061, 0.121]}
      />
      <mesh
        geometry={nodes.toad_3b003.geometry}
        material={materials["plants.040"]}
        position={[8.602, 1.625, -6.337]}
        rotation={[2.956, -0.396, -2.894]}
        scale={[0.131, 0.097, 0.131]}
      />
      <mesh
        geometry={nodes.toad_3b004.geometry}
        material={materials["plants.041"]}
        position={[-2.165, 1.677, -6.674]}
        rotation={[-0.082, -0.195, -0.246]}
        scale={[0.152, 0.113, 0.152]}
      />
      <mesh
        geometry={nodes.toad_2006.geometry}
        material={materials["plants.042"]}
        position={[-5.811, 5.682, -0.593]}
        rotation={[2.865, 0.946, -2.959]}
        scale={[0.115, 0.059, 0.115]}
      />
      <mesh
        geometry={nodes.toad_1b003.geometry}
        material={materials["plants.043"]}
        position={[-2.116, 5.401, 4.488]}
        rotation={[2.4, 0.763, -2.708]}
        scale={[0.121, 0.061, 0.121]}
      />
      <mesh
        geometry={nodes.toad_1b004.geometry}
        material={materials["plants.044"]}
        position={[9.314, 1.545, 1.443]}
        rotation={[-2.483, 1.134, 1.862]}
        scale={[0.121, 0.061, 0.121]}
      />
      <mesh
        geometry={nodes.toad_1b005.geometry}
        material={materials["plants.045"]}
        position={[8.355, 1.44, -0.104]}
        rotation={[3.055, 0.669, -2.732]}
        scale={[0.121, 0.061, 0.121]}
      />
      <mesh
        geometry={nodes.toad_2007.geometry}
        material={materials["plants.046"]}
        position={[3.277, 1.521, -9.265]}
        rotation={[-0.744, 0.072, -0.154]}
        scale={[0.067, 0.034, 0.067]}
      />
      <mesh
        geometry={nodes.toad_1b006.geometry}
        material={materials["plants.047"]}
        position={[1.867, 1.486, 0.451]}
        rotation={[-3.071, 0.833, 3.041]}
        scale={[0.121, 0.061, 0.121]}
      />
      <mesh
        geometry={nodes.grass_1a020.geometry}
        material={materials["plants.048"]}
        position={[6.737, 1.478, -3.325]}
        rotation={[-1.149, 0.958, 0.892]}
        scale={[0.025, 0.034, 0.001]}
      />
      <mesh
        geometry={nodes.cover_wood_3002.geometry}
        material={materials["trunck.001"]}
        position={[9.229, 1.455, -1.261]}
        rotation={[1.635, -0.241, -2.228]}
        scale={[0.015, 0.33, 0.055]}
      />
      <mesh
        geometry={nodes.grass_3010.geometry}
        material={materials["plants.050"]}
        position={[9.853, 1.398, -1.504]}
        rotation={[-2.608, -1.152, -2.684]}
        scale={[0.074, 0.074, 0.065]}
      />
      <mesh
        geometry={nodes.toad_2008.geometry}
        material={materials["plants.049"]}
        position={[9.296, 1.516, -0.866]}
        rotation={[-2.742, -0.623, -2.946]}
        scale={[0.104, 0.053, 0.104]}
      />
      <mesh
        geometry={nodes.toad_3b005.geometry}
        material={materials["plants.049"]}
        position={[8.904, 1.642, -0.648]}
        rotation={[0.517, 1.181, -0.651]}
        scale={[0.153, 0.114, 0.153]}
      />
      <mesh
        geometry={nodes.rock_2009.geometry}
        material={materials["Material.063"]}
        position={[6.897, 1.54, -2.088]}
        rotation={[2.62, -0.437, -2.354]}
        scale={0.922}
      />
      <mesh
        geometry={nodes.Cone001.geometry}
        material={materials.piky_tex}
        position={[-5.549, 4.635, 6.575]}
        rotation={[0.009, 0.366, -0.085]}
        scale={[2.671, 2.658, 2.658]}
      />
      <mesh
        geometry={nodes.Cone004.geometry}
        material={materials.obsidiana}
        position={[-5.549, 4.635, 6.575]}
        rotation={[0.009, 0.366, -0.085]}
        scale={[2.671, 2.658, 2.658]}
      />
      <group
        position={[1.11, -0.014, 0.564]}
        rotation={[0, 0.42, 0]}
        scale={[10, 11.442, 10]}
      >
        <mesh
          geometry={nodes.Icosphere031.geometry}
          material={materials["green.001"]}
        />
        <mesh
          geometry={nodes.Icosphere031_1.geometry}
          material={materials["brown.001"]}
        />
        <mesh
          geometry={nodes.Icosphere031_2.geometry}
          material={materials["blue.001"]}
        />
      </group>
      <mesh
        geometry={nodes.rock_5004.geometry}
        material={materials["Material.064"]}
        position={[-0.661, 1.47, 4.582]}
        rotation={[1.325, 0.024, 2.259]}
        scale={[0.417, 0.516, 1.154]}
      />
      <mesh
        geometry={nodes.rock_5005.geometry}
        material={materials["Material.065"]}
        position={[7.186, 0.729, 3.027]}
        rotation={[1.655, -0.137, 1.619]}
        scale={[0.2, 0.248, 0.553]}
      />
      <mesh
        geometry={nodes.grass_1a021.geometry}
        material={materials["plants.051"]}
        position={[1.342, 1.348, 3.027]}
        rotation={[-0.227, -1.14, 0.988]}
        scale={[0.02, 0.023, 0.001]}
      />
      <mesh
        geometry={nodes.grass_3011.geometry}
        material={materials["plants.052"]}
        position={[0.591, 1.416, -0.336]}
        rotation={[0, 0.941, 0]}
        scale={[0.074, 0.074, 0.065]}
      />
      <mesh
        geometry={nodes.toad_2009.geometry}
        material={materials["plants.053"]}
        position={[2.486, 1.754, -5.261]}
        rotation={[-0.097, 0.615, -0.198]}
        scale={[0.104, 0.053, 0.104]}
      />
      <mesh
        geometry={nodes.toad_3b006.geometry}
        material={materials["plants.054"]}
        position={[3.101, 1.68, -5.493]}
        rotation={[-3.048, 0.539, 2.863]}
        scale={[0.128, 0.095, 0.128]}
      />
      <mesh
        geometry={nodes.cover_wood_3003.geometry}
        material={materials["trunckdos.002"]}
        position={[2.904, 1.608, -5.14]}
        rotation={[-1.73, -0.013, -2.07]}
        scale={[0.008, 0.188, 0.031]}
      />
      <mesh
        geometry={nodes.rock_2007.geometry}
        material={materials["Material.067"]}
        position={[-2.319, 0.803, -0.947]}
        rotation={[-0.15, -1.239, 1.491]}
        scale={0.831}
      />
      <mesh
        geometry={nodes.hut_top.geometry}
        material={materials["Material.004"]}
        position={[-1.074, 1.647, -4.427]}
        rotation={[Math.PI, -0.622, Math.PI]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.hut_mid.geometry}
        material={materials["Material.005"]}
        position={[-1.074, 1.553, -4.427]}
        rotation={[Math.PI, -0.622, Math.PI]}
        scale={[0.04, 0.047, 0.04]}
      />
      <mesh
        geometry={nodes.hut_bot.geometry}
        material={materials["HUT  TOP"]}
        position={[-0.839, 1.552, -4.53]}
        rotation={[-1.581, 0.335, -3.109]}
        scale={[0.016, 0.369, 0.061]}
      />
      <mesh
        geometry={nodes.hut_carpet.geometry}
        material={materials["Material.006"]}
        position={[-1.069, 1.534, -4.447]}
        rotation={[Math.PI, -0.387, Math.PI]}
        scale={[-0.56, -0.068, -0.56]}
      />
      <mesh
        geometry={nodes.rock_5001.geometry}
        material={materials["Material.020"]}
        position={[-2.898, 1.289, 0.947]}
        rotation={[1.317, 0.849, -1.376]}
        scale={[0.566, 0.504, 0.504]}
      />
      <mesh
        geometry={nodes.hut_small001.geometry}
        material={materials["Material.021"]}
        position={[0.072, 1.509, -7.259]}
        rotation={[Math.PI, -0.001, Math.PI]}
        scale={[0.022, 0.035, 0.022]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials["stoneFloor.001"]}
        position={[1.695, 1.508, -6.202]}
        rotation={[-0.014, -0.667, 0.02]}
        scale={[0.063, 0.017, 0.063]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials["Material.023"]}
        position={[3.413, 1.495, -3.768]}
        rotation={[3.101, 1.169, 0.031]}
        scale={[0.038, 0.04, 0.065]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["Material.022"]}
        position={[1.798, 1.504, -7.671]}
        rotation={[-0.005, -0.161, -0.03]}
        scale={[0.062, 0.019, 0.062]}
      />
      <mesh
        geometry={nodes.hut_small003.geometry}
        material={materials.Tex_house}
        position={[5.019, 1.493, -4.147]}
        rotation={[-3.082, -1.469, -3.099]}
        scale={[0.023, 0.035, 0.023]}
      />
      <mesh
        geometry={nodes.hut_small005.geometry}
        material={materials.tex_house_02}
        position={[4.342, 1.497, -8.143]}
        rotation={[-3.121, 1.202, 3.077]}
        scale={[0.022, 0.031, 0.022]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["Material.028"]}
        position={[4.397, 1.502, -7.184]}
        rotation={[-3.124, -0.019, -3.133]}
        scale={[0.053, 0.013, 0.053]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Material.029"]}
        position={[3.889, 1.51, -5.963]}
        rotation={[-0.019, 0.257, 0.002]}
        scale={[0.063, 0.022, 0.063]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials["Material.030"]}
        position={[3.266, 1.509, -4.292]}
        rotation={[-0.015, 0.399, -0.009]}
        scale={[0.069, 0.031, 0.069]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["Material.031"]}
        position={[2.095, 1.51, -6.524]}
        rotation={[3.021, 1.03, 0.141]}
        scale={[0.037, 0.026, 0.063]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials["Material.032"]}
        position={[1.962, 1.498, -4.431]}
        rotation={[-0.008, -0.508, 0.011]}
        scale={[0.065, 0.027, 0.064]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials["Material.033"]}
        position={[3.775, 1.493, -4.634]}
        rotation={[3.116, 0.61, 0.022]}
        scale={[0.042, 0.036, 0.072]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials["Material.034"]}
        position={[1.29, 1.513, -6.993]}
        rotation={[0.126, 1.5, -0.162]}
        scale={[0.062, 0.017, 0.062]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials["Material.035"]}
        position={[3.389, 1.502, -6.496]}
        rotation={[0.033, 0.978, 3.116]}
        scale={[0.033, 0.019, 0.064]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials["Material.036"]}
        position={[4.008, 1.493, -5.273]}
        rotation={[3.124, -0.069, -0.001]}
        scale={[0.039, 0.031, 0.067]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials["Material.037"]}
        position={[2.549, 1.511, -4.206]}
        rotation={[-3.062, -1.413, -3.069]}
        scale={[0.067, 0.028, 0.067]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials["stoneFloor.002"]}
        position={[1.405, 1.494, -5.616]}
        rotation={[-0.008, -0.138, -0.018]}
        scale={[0.062, 0.032, 0.075]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials["Material.038"]}
        position={[2.751, 1.492, -6.575]}
        rotation={[0.424, 1.473, 2.701]}
        scale={[0.035, 0.036, 0.068]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials["Material.039"]}
        position={[4.604, 1.508, -6.678]}
        rotation={[-3.037, -0.932, -3.053]}
        scale={[0.051, 0.013, 0.051]}
      />
      <mesh
        geometry={nodes.hut_small006.geometry}
        material={materials["Material.041"]}
        position={[6.682, 1.488, -6.327]}
        rotation={[0.037, 0.652, -0.017]}
        scale={[0.022, 0.03, 0.022]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={materials["Material.043"]}
        position={[4.952, 1.507, -6.305]}
        rotation={[-3.133, -0.603, 3.13]}
        scale={[0.055, 0.019, 0.055]}
      />
      <mesh
        geometry={nodes.fence_1002.geometry}
        material={materials["Material.045"]}
        position={[0.649, 1.839, -3.75]}
        rotation={[0.302, -1.405, -2.827]}
        scale={[-0.375, -0.053, -0.413]}
      />
      <mesh
        geometry={nodes.fence_2001.geometry}
        material={materials["Material.046"]}
        position={[2.521, 1.417, -1.344]}
        rotation={[0.015, -0.118, -0.031]}
        scale={[-0.382, -0.054, -0.421]}
      />
      <mesh
        geometry={nodes.Cube033.geometry}
        material={materials["Material.047"]}
        position={[2.681, 1.467, 0.312]}
        rotation={[0.025, 1.202, -3.118]}
        scale={[0.035, 0.023, 0.06]}
      />
      <mesh
        geometry={nodes.Cube034.geometry}
        material={materials["Material.048"]}
        position={[2.986, 1.488, -0.191]}
        rotation={[0.002, -0.368, 0.005]}
        scale={[0.06, 0.02, 0.06]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={materials["Material.049"]}
        position={[3.207, 1.503, -0.745]}
        rotation={[0.048, 1.169, 3.099]}
        scale={[0.035, 0.034, 0.06]}
      />
      <mesh
        geometry={nodes.box001.geometry}
        material={materials["Material.050"]}
        position={[0.616, 1.45, -6.334]}
        rotation={[Math.PI, -0.42, Math.PI]}
        scale={[-0.212, -0.03, -0.234]}
      />
      <mesh
        geometry={nodes.Cube036.geometry}
        material={materials["Material.051"]}
        position={[3.535, 1.488, -1.217]}
        rotation={[-3.129, 0.394, -0.011]}
        scale={[0.037, 0.031, 0.063]}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={materials["Material.054"]}
        position={[3.784, 1.514, -2.618]}
        rotation={[0, 0.088, -0.01]}
        scale={[0.069, 0.025, 0.069]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={materials["Material.053"]}
        position={[3.654, 1.495, -1.96]}
        rotation={[-0.039, 1.454, -3.08]}
        scale={[0.039, 0.036, 0.066]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={materials["Material.052"]}
        position={[3.69, 1.492, -3.239]}
        rotation={[-0.018, -1.124, 0.033]}
        scale={[0.069, 0.031, 0.069]}
      />
      <mesh
        geometry={nodes.tree_1001.geometry}
        material={materials.trees}
        position={[5.796, 0.676, -8.911]}
        rotation={[0, 0.453, 0]}
        scale={[0.22, 0.259, 0.22]}
      />
      <mesh
        geometry={nodes.tree_1002.geometry}
        material={materials["trees.002"]}
        position={[6.734, 2.032, 3.163]}
        rotation={[0, 0.453, 0]}
        scale={[0.254, 0.299, 0.254]}
      />
      <mesh
        geometry={nodes.tree_2001.geometry}
        material={materials["trees.003"]}
        position={[5.192, 1.325, 1.016]}
        rotation={[0, 0.852, 0]}
        scale={[0.123, 0.145, 0.123]}
      />
      <mesh
        geometry={nodes.tree_1003.geometry}
        material={materials["trees.004"]}
        position={[6.854, 1.278, 0.785]}
        rotation={[0, 1.495, 0]}
        scale={[0.25, 0.295, 0.25]}
      />
      <mesh
        geometry={nodes.tree_3001.geometry}
        material={materials["trees.005"]}
        position={[8.05, 1.221, 0.117]}
        rotation={[2.824, 0.455, -2.843]}
        scale={[0.127, 0.149, 0.127]}
      />
      <mesh
        geometry={nodes.tree_2002.geometry}
        material={materials.trees}
        position={[2.744, 1.011, -9.446]}
        rotation={[0, -0.069, 0]}
        scale={[0.199, 0.235, 0.199]}
      />
      <mesh
        geometry={nodes.tree_2003.geometry}
        material={materials["trees.007"]}
        position={[8.41, 1.47, -5.835]}
        rotation={[0, -0.733, 0]}
        scale={[0.162, 0.191, 0.162]}
      />
      <mesh
        geometry={nodes.tree_1004.geometry}
        material={materials["trees.009"]}
        position={[-2.79, 4.166, 1.979]}
        rotation={[0, -1.294, 0]}
        scale={[0.214, 0.251, 0.214]}
      />
      <mesh
        geometry={nodes.tree_2004.geometry}
        material={materials["trees.008"]}
        position={[-3.652, 4.76, 0.644]}
        rotation={[0, -1.403, 0]}
        scale={[0.13, 0.153, 0.13]}
      />
      <mesh
        geometry={nodes.tree_1005.geometry}
        material={materials["trees.010"]}
        position={[-1.963, 1.136, -2.937]}
        rotation={[-0.044, 1.503, 0.066]}
        scale={[0.206, 0.243, 0.206]}
      />
      <mesh
        geometry={nodes.tree_1006.geometry}
        material={materials["trees.011"]}
        position={[-2.855, 1.022, -6.212]}
        rotation={[0, 0.791, 0]}
        scale={[0.308, 0.362, 0.308]}
      />
      <mesh
        geometry={nodes.tree_3002.geometry}
        material={materials["trees.012"]}
        position={[-2.533, 1.391, -6.583]}
        rotation={[-Math.PI, 1.2, -Math.PI]}
        scale={[0.135, 0.159, 0.135]}
      />
      <mesh
        geometry={nodes.tree_1007.geometry}
        material={materials["trees.013"]}
        position={[1.389, 3.462, 7.042]}
        rotation={[0, -0.914, 0]}
        scale={[0.235, 0.277, 0.235]}
      />
      <mesh
        geometry={nodes.tree_3003.geometry}
        material={materials["trees.014"]}
        position={[-1.669, 4.898, 5.149]}
        rotation={[2.034, 1.257, -2.098]}
        scale={[0.103, 0.121, 0.103]}
      />
      <mesh
        geometry={nodes.tree_2005.geometry}
        material={materials["trees.015"]}
        position={[9.122, 1.458, 1.618]}
        rotation={[0, 0.371, 0]}
        scale={[0.184, 0.217, 0.184]}
      />
      <mesh
        geometry={nodes.tree_1008.geometry}
        material={materials["trees.016"]}
        position={[-6.272, 5.001, -0.424]}
        rotation={[Math.PI, -0.684, Math.PI]}
        scale={[0.223, 0.262, 0.223]}
      />
      <mesh
        geometry={nodes.tree_1009.geometry}
        material={materials["trees.017"]}
        position={[10.703, 0.603, 0.604]}
        rotation={[Math.PI, -1.475, Math.PI]}
        scale={[0.268, 0.275, 0.268]}
      />
      <mesh
        geometry={nodes.tree_1010.geometry}
        material={materials["trees.018"]}
        position={[1.431, 1.292, -2.47]}
        rotation={[Math.PI, -0.764, Math.PI]}
        scale={[0.25, 0.267, 0.25]}
      />
      <mesh
        geometry={nodes.cover_wood_3005.geometry}
        material={materials["trunckdos.001"]}
        position={[-2.013, 1.596, -6.293]}
        rotation={[-1.517, 0.15, 2.215]}
        scale={[0.014, 0.311, 0.052]}
      />
      <mesh
        geometry={nodes.box002.geometry}
        material={materials["Material.055"]}
        position={[5.469, 1.469, -6.832]}
        rotation={[Math.PI, -0.42, Math.PI]}
        scale={[-0.213, -0.03, -0.235]}
      />
      <mesh
        geometry={nodes.barrel_2001.geometry}
        material={materials["Material.056"]}
        position={[5.502, 1.685, -7.475]}
        rotation={[0.052, 0.415, 0.111]}
        scale={[-0.275, -0.039, -0.303]}
      />
      <mesh
        geometry={nodes.cart001.geometry}
        material={materials["Material.056"]}
        position={[5.369, 1.633, -7.476]}
        rotation={[-0.008, 0.747, 0.198]}
        scale={[-0.181, -0.025, -0.2]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["Material.057"]}
        position={[5.169, 1.507, -5.852]}
        rotation={[-3.141, -0.358, -3.137]}
        scale={[0.055, 0.022, 0.055]}
      />
      <mesh
        geometry={nodes.toad_1b001.geometry}
        material={materials["plants.001"]}
        position={[-1.554, 1.592, -6.669]}
        rotation={[-3.13, 1.16, 3.124]}
        scale={[0.121, 0.061, 0.121]}
      />
      <mesh
        geometry={nodes.toad_2001.geometry}
        material={materials["plants.001"]}
        position={[-1.654, 1.603, -6.986]}
        rotation={[2.757, 0.939, -3.009]}
        scale={[0.104, 0.053, 0.104]}
      />
      <mesh
        geometry={nodes.grass_1a001.geometry}
        material={materials["plants.002"]}
        position={[-1.44, 1.495, -6.877]}
        rotation={[-0.163, 0.382, 0.114]}
        scale={[0.014, 0.014, 0.001]}
      />
      <mesh
        geometry={nodes.toad_2002.geometry}
        material={materials["plants.003"]}
        position={[4.549, 1.526, 0.729]}
        rotation={[-0.134, 0.415, -0.067]}
        scale={[0.104, 0.053, 0.104]}
      />
      <mesh
        geometry={nodes.toad_3b001.geometry}
        material={materials["plants.003"]}
        position={[4.999, 1.603, 0.634]}
        rotation={[-3.109, -0.964, 2.959]}
        scale={[0.153, 0.114, 0.153]}
      />
      <mesh
        geometry={nodes.grass_3001.geometry}
        material={materials["plants.004"]}
        position={[1.846, 1.412, -0.504]}
        rotation={[0, 0.941, 0]}
        scale={[0.074, 0.074, 0.065]}
      />
      <mesh
        geometry={nodes.grass_1a002.geometry}
        material={materials["plants.005"]}
        position={[7.855, 1.389, -7.102]}
        rotation={[2.997, 0.089, -2.919]}
        scale={[0.019, 0.018, 0.001]}
      />
      <mesh
        geometry={nodes.toad_2003.geometry}
        material={materials["plants.005"]}
        position={[8.044, 1.557, -6.783]}
        rotation={[-0.122, 0.508, -0.306]}
        scale={[0.067, 0.034, 0.067]}
      />
      <mesh
        geometry={nodes.rock_2001.geometry}
        material={materials["Material.066"]}
        position={[-2.874, 0.902, -0.242]}
        rotation={[-2.991, -0.607, -1.341]}
        scale={1.244}
      />
      <mesh
        geometry={nodes.tree_1011.geometry}
        material={materials["trees.001"]}
        position={[1.528, 1.262, 0.599]}
        rotation={[0, 1.495, 0]}
        scale={[0.175, 0.206, 0.175]}
      />
      <mesh
        geometry={nodes.tree_2006.geometry}
        material={materials["trees.019"]}
        position={[3.376, 1.281, 1.765]}
        rotation={[-Math.PI, 0.84, -Math.PI]}
        scale={[0.107, 0.125, 0.107]}
      />
      <mesh
        geometry={nodes.tree_1012.geometry}
        material={materials["trees.020"]}
        position={[8.859, 1.202, -4.601]}
        rotation={[Math.PI, -1.531, Math.PI]}
        scale={[0.274, 0.322, 0.274]}
      />
      <mesh
        geometry={nodes.fence_1003.geometry}
        material={materials["Material.024"]}
        position={[2.488, 1.495, -2.631]}
        rotation={[-3.128, -0.187, -3.141]}
        scale={[-0.393, -0.055, -0.433]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["Material.026"]}
        position={[1.846, 1.504, -7.087]}
        rotation={[2.905, 1.262, -2.932]}
        scale={[0.062, 0.022, 0.062]}
      />
      <mesh
        geometry={nodes.rock_3001.geometry}
        material={materials["Material.001"]}
        position={[-3.06, 4.343, 0.379]}
        rotation={[-2.537, -0.863, -1.156]}
        scale={[0.969, 0.959, 0.787]}
      />
      <mesh
        geometry={nodes.rock_5002.geometry}
        material={materials["Material.003"]}
        position={[-3.227, 4.748, -1.852]}
        rotation={[-0.361, 1.074, 0.085]}
        scale={[0.67, 0.387, 0.588]}
      />
      <mesh
        geometry={nodes.rock_2002.geometry}
        material={materials["Material.002"]}
        position={[-3.397, 4.124, -1.2]}
        rotation={[0.233, -0.373, -2.244]}
        scale={[0.363, 0.408, 0.652]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={materials["stone.001"]}
        position={[-0.763, 0.92, 2.355]}
        rotation={[0.324, 0.831, 0.024]}
        scale={[0.237, 0.399, 0.215]}
      />
      <mesh
        geometry={nodes.trunk_2.geometry}
        material={materials.trunck}
        position={[7.853, 1.5, -6.489]}
        rotation={[3.098, 0.775, -3.041]}
        scale={0.139}
      />
      <mesh
        geometry={nodes.toad_3b.geometry}
        material={materials.plants}
        position={[8.059, 1.663, -5.803]}
        rotation={[3.026, -0.668, 2.644]}
        scale={[0.131, 0.097, 0.131]}
      />
      <mesh
        geometry={nodes.toad_1b.geometry}
        material={materials.plants}
        position={[7.703, 1.557, -6.741]}
        rotation={[-0.158, 0.436, -0.078]}
        scale={[0.076, 0.039, 0.076]}
      />
      <mesh
        geometry={nodes.rock_6.geometry}
        material={materials["Material.014"]}
        position={[10.491, -1.179, -2.372]}
        rotation={[2.747, -0.503, 3.073]}
        scale={[0.364, 0.613, 0.331]}
      />
      <mesh
        geometry={nodes.rock_5.geometry}
        material={materials["Material.015"]}
        position={[4.544, 1.3, 2.99]}
        rotation={[0.295, 0.135, 1.757]}
        scale={[0.598, 0.505, 0.528]}
      />
      <mesh
        geometry={nodes.rock_4.geometry}
        material={materials["Material.016"]}
        position={[1.087, 0.666, 3.598]}
        rotation={[-Math.PI, 0.522, -Math.PI]}
        scale={[0.866, 0.968, 0.866]}
      />
      <mesh
        geometry={nodes.rock_3.geometry}
        material={materials["Material.019"]}
        position={[10.925, 1.028, -0.635]}
        rotation={[-2.742, -0.676, -1.536]}
        scale={[0.982, 0.972, 0.798]}
      />
      <mesh
        geometry={nodes.rock_2.geometry}
        material={materials["Material.018"]}
        position={[-2.835, 1.057, -1.894]}
        rotation={[-0.02, 0.331, 1.635]}
        scale={1.15}
      />
      <mesh
        geometry={nodes.rock_1.geometry}
        material={materials["Material.017"]}
        position={[3.614, 0.668, -9.262]}
        rotation={[0.439, 0.396, -1.117]}
        scale={[0.777, 0.4, 0.893]}
      />
      <mesh
        geometry={nodes.grass_3.geometry}
        material={materials.plants}
        position={[3.832, 1.441, 1.187]}
        rotation={[0, 0.941, 0]}
        scale={[0.074, 0.074, 0.065]}
      />
      <mesh
        geometry={nodes.grass_1a.geometry}
        material={materials.plants}
        position={[1.728, 1.457, -1.838]}
        rotation={[-0.364, -1.187, -0.197]}
        scale={[0.018, 0.017, 0.001]}
      />
      <mesh
        geometry={nodes.bush.geometry}
        material={materials.plants}
        position={[6.713, 1.594, -2.878]}
        rotation={[-0.023, 0.05, 0.655]}
        scale={[0.293, 0.077, 0.293]}
      />
    </group>
  );
}

useGLTF.preload("./public/models/farm.glb");
